### ISSUE TITLE
I noticed this, but I didn't manage to implement it, how should I implement it specifically?

### ISSUE THREAD

**Issue by penq123** [GrammaTech/gtirb-rewriting#13]
class AllFunctionsScope(Scope):
    """
    Specifies that an insertion should happen either in the entry blocks or
    exit blocks of functions. The functions that this inserts into can be
    controlled with a list of names (or regular expressions) to check the name
    against.
    """

**Comment by pranjalsingh008** [comment]
Hey, any update on this?

**Comment by pranjalsingh008** [comment]
This is the test program I'm using to replace a instruction at an address with `nop` 
```
from gtirb_rewriting import *
import gtirb_rewriting.driver
from gtirb_capstone.instructions import GtirbInstructionDecoder
import logging
import gtirb

class ReplaceInstructionPass(Pass):

    def __init__(self):
        self.target_address = 0x118b

    def begin_module(self, module, functions, context):

        decoder = GtirbInstructionDecoder(module.isa)

        for function in functions:
            for block in function.get_all_blocks():
                offset = 0
                for instruction in decoder.get_instructions(block):
                    if instruction.address  == self.target_address:
                        context.replace_at(block, offset, instruction.size,'nop')
                        logging.debug(f"Inserted at {hex(instruction.address)}")

                        return
                    offset += instruction.size

if __name__ == "__main__":

    logging.basicConfig(level=logging.DEBUG)
    gtirb_rewriting.driver.main(ReplaceInstructionPass)
```
But this keeps giving me the said error: 
```
DEBUG:root:Inserted at 0x118b
DEBUG:gtirb_rewriting:Applying bytes at CodeBlock(uuid=UUID('00a01ffa-3bb7-44c7-a82e-65d78911a645'), size=12, offset=0, decode_mode=CodeBlock.DecodeMode.Default, )+0
DEBUG:gtirb_rewriting:Applying nop at CodeBlock(uuid=UUID('00a01ffa-3bb7-44c7-a82e-65d78911a645'), size=12, offset=0, decode_mode=CodeBlock.DecodeMode.Default, )+0
DEBUG:gtirb_rewriting:  Before:
DEBUG:gtirb_rewriting:	0x118b:	lea	rdi, [rip + 0xe72]
DEBUG:gtirb_rewriting:	# +3: SymAddrConst: .L_2004 + 0
DEBUG:gtirb_rewriting:	0x1192:	call	0x1050
DEBUG:gtirb_rewriting:	# +1: SymAddrConst: FUN_1050 + 0 {SymbolicExpression.Attribute.PLT}
Traceback (most recent call last):
  File "patch.py", line 53, in <module>
    gtirb_rewriting.driver.main(ReplaceInstructionPass)
  File "/usr/local/lib/python3.8/dist-packages/gtirb_rewriting/driver.py", line 350, in main
    _driver_core([entrypoint], False, argv)
  File "/usr/local/lib/python3.8/dist-packages/gtirb_rewriting/driver.py", line 316, in _driver_core
    pass_man.run(ir)
  File "/usr/local/lib/python3.8/dist-packages/gtirb_rewriting/passes.py", line 116, in run
    context.apply()
  File "/usr/local/lib/python3.8/dist-packages/gtirb_rewriting/rewriting.py", line 1115, in apply
    self._apply_modifications(
  File "/usr/local/lib/python3.8/dist-packages/gtirb_rewriting/rewriting.py", line 660, in _apply_modifications
    actual_block, insert_len = self._insert_assembler_result(
  File "/usr/local/lib/python3.8/dist-packages/gtirb_rewriting/rewriting.py", line 529, in _insert_assembler_result
    new_end = _modify_block_insert(
  File "/usr/local/lib/python3.8/dist-packages/gtirb_rewriting/modify.py", line 987, in _modify_block_insert
    assert isinstance(text_section.blocks[0], gtirb.CodeBlock)
AssertionError
```
I'm not sure what this error is trying to say, the `.text` has blocks other than a `CodeBlock`? @jranieri-grammatech

**Comment by jranieri-grammatech** [comment]
I think the problem is that you're passing a string instead of a `Patch` object to `replace_at`. I'd recommend you use a static type checker like mypy or pyright to catch bugs like this.

This version should work, though I haven't tested it:
```python
from gtirb_rewriting import *
import gtirb_rewriting.driver
from gtirb_capstone.instructions import GtirbInstructionDecoder
import logging
import gtirb

class ReplaceInstructionPass(Pass):

    def __init__(self):
        self.target_address = 0x118b

    def begin_module(self, module, functions, context):

        decoder = GtirbInstructionDecoder(module.isa)

        for function in functions:
            for block in function.get_all_blocks():
                offset = 0
                for instruction in decoder.get_instructions(block):
                    if instruction.address  == self.target_address:
                        context.replace_at(block, offset, instruction.size, Patch.from_function(self.nop_patch))
                        logging.debug(f"Inserted at {hex(instruction.address)}")

                        return
                    offset += instruction.size

    @patch_constraints
    def nop_patch(self, context):
        return "nop"

if __name__ == "__main__":

    logging.basicConfig(level=logging.DEBUG)
    gtirb_rewriting.driver.main(ReplaceInstructionPass)
```

**Comment by pranjalsingh008** [comment]
Thanks! this did work, but it didn't give the expected results. I'm unsure what went wrong. I have a few more questions about this. Is there a better way to communicate about this issue instead of creating multiple issues? Perhaps a dedicated space where people can ask questions or share doubts related to this tool?
